services:
  postgres:
    container_name: postgres{{ cookiecutter.docker_title }}Development
    image: postgres:latest
    restart: on-failure
    ports:
      - 5431:5432
    env_file:
      - ./src/core/.dev.env
